apiVersion: v1
kind: Service
metadata:
  name: argoapp
  labels:
    app: argoapp
spec:
  selector:
    app: argoapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
